### ISSUE TITLE
Path Traversal through "Word/s" input! (note: not the intended file name input)

### ISSUE THREAD

**Issue by TheBinitGhimire** [TheNittam/Pass2Pwn#1]
Hi there,

There is a Path Traversal vulnerability in this project, through the input word/words. Yes, path traversal is intended for the filename input since it depends on the user on where the file should be saved and how, however, I guess it isn't intended for the word/words input too.

For example, if I give input as "../nice" for "Word/s" and go with the default file name, then the password list generated is totally fine, however there is no proper sanitization to avoid dot-dot-slash (or simply slash) to prevent path traversal through the word/words input.

**Note**: Path traversal through filename input mayn't count as a vulnerability, since that's the file path decided by the user. But, this isn't the focus of this issue I am opening up, and instead this is about the word/words input.

## How it should be working?
If I give input as "../nice" for "Word/s", then the default file name prefix should be one of these: "nice", ".._nice", "..nice".

I am opening up a Pull Request alongside this Issue, where I have implemented a fix for the issue. I hope you would check that out after going through this issue.

Thanks,
@TheBinitGhimire

**Comment by TheNittam** [comment]
**Pass2Pwn** has no security measures because I didn't think anyone would care about it because it isn't the finest tool on the market, but you took the time to look into it and made a patch, which is really appreciated.

**Thanks**

**Comment by TheBinitGhimire** [comment]
**_Thanks for merging the patch!_**
